const prefix = '@employee';

export const EmployeeActionTypes = {
  LOAD_EMPLOYEE_LIST_REQUEST: `${prefix}/LOAD_EMPLOYEE_LIST_REQUEST`,
  LOAD_EMPLOYEE_LIST_SUCCEEDED: `${prefix}/LOAD_EMPLOYEE_LIST_SUCCEEDED`,

  CREATE_EMPLOYEE_REQUEST: `${prefix}/CREATE_EMPLOYEE_REQUEST`,
  CREATE_EMPLOYEE_SUCCEEDED: `${prefix}/CREATE_EMPLOYEE_SUCCEEDED`,

  DELETE_EMPLOYEE_REQUEST: `${prefix}/DELETE_EMPLOYEE_REQUEST`,
  DELETE_EMPLOYEE_SUCCEEDED: `${prefix}/DELETE_EMPLOYEE_SUCCEEDED`,

  LOAD_JOB_LIST_REQUEST: `${prefix}/LOAD_JOB_LIST_REQUEST`,
  LOAD_JOB_LIST_SUCCEEDED: `${prefix}/LOAD_JOB_LIST_SUCCEEDED`,
};
